'use client'

import { useState } from 'react'
import type { Product } from '@/lib/commerce-engine'
import { ArrowLeft, Check, CreditCard, ShieldCheck } from 'lucide-react'

type CartItem = { product: Product; quantity: number }
type OrderItem = { id: string; items: CartItem[]; total: number; address: string; payment: string; status: string; eta: string }
type Props = { cart: CartItem[]; setCart: (items: CartItem[]) => void; onOrder: (order: OrderItem) => void }
type Stage = 'cart' | 'delivery' | 'payment' | 'review' | 'confirmed'
const money = (p: Product, n = p.price) => `${p.currency === 'INR' ? '₹' : '$'}${n.toLocaleString('en-IN')}`

export function CheckoutWorkspace({ cart, setCart, onOrder }: Props) {
  const [stage, setStage] = useState<Stage>('cart'); const [name, setName] = useState(''); const [address, setAddress] = useState(''); const [payment, setPayment] = useState('Sandbox card'); const [message, setMessage] = useState(''); const [order, setOrder] = useState<OrderItem>()
  const subtotal = cart.reduce((sum, item) => sum + item.product.price * item.quantity, 0); const shipping = subtotal > 5000 ? 0 : 99; const tax = Math.round(subtotal * .18); const total = subtotal + shipping + tax
  function update(id: string, quantity: number) { setCart(cart.map(item => item.product.id === id ? { ...item, quantity: Math.max(1, Math.min(10, quantity || 1)) } : item)) }
  function next() { if (stage === 'cart') setStage('delivery'); else if (stage === 'delivery') { if (name.trim().length < 2 || address.trim().length < 8) return setMessage('Enter a complete name and delivery address.') ; setMessage(''); setStage('payment') } else if (stage === 'payment') setStage('review') }
  function confirm() { if (!name || !address || !payment) return setMessage('Complete delivery and payment details first.'); const created = { id: `SG-${Date.now().toString().slice(-6)}`, items: cart, total, address: `${name}, ${address}`, payment, status: 'Confirmed', eta: '3–5 business days' }; setOrder(created); setStage('confirmed'); onOrder(created); setCart([]) }
  if (!cart.length && stage !== 'confirmed') return <section className="panel empty-workspace"><h2>Your cart is empty</h2><p>Add a product from Shopping agent. Nothing is added automatically.</p></section>
  if (stage === 'confirmed' && order) return <section className="checkout-workspace panel"><div className="checkout-main"><span className="result-kicker">ORDER CONFIRMED</span><h2>Your order is confirmed</h2><p><Check /> {order.id} is saved to My Orders. Expected delivery: {order.eta}.</p>{order.items.map(item => <div className="order-product" key={item.product.id}><div className="product-image">{item.product.image && <img src={item.product.image} alt={item.product.title} />}</div><div><strong>{item.product.title}</strong><p>{item.product.store} · Quantity {item.quantity} · {money(item.product, item.product.price * item.quantity)}</p></div></div>)}</div></section>
  return <section className="checkout-workspace panel" aria-label="Purchase flow"><div className="checkout-main"><span className="result-kicker">{stage === 'cart' ? 'CART' : stage === 'delivery' ? 'DELIVERY DETAILS' : stage === 'payment' ? 'PAYMENT' : 'FINAL ORDER REVIEW'}</span><h2>{stage === 'cart' ? 'Review your cart' : stage === 'review' ? 'Review before placing order' : 'Purchase workspace'}</h2>{stage === 'cart' && cart.map(item => <div className="order-product" key={item.product.id}><div className="product-image">{item.product.image && <img src={item.product.image} alt={item.product.title} />}</div><div><strong>{item.product.title}</strong><p>{item.product.store} · {money(item.product)}</p><label className="quantity-control">Quantity <input type="number" min="1" max="10" value={item.quantity} onChange={event => update(item.product.id, Number(event.target.value))} /></label></div></div>)}{stage === 'delivery' && <div className="purchase-form"><label>Name<input value={name} onChange={event => setName(event.target.value)} placeholder="Your name" /></label><label>Delivery address<input value={address} onChange={event => setAddress(event.target.value)} placeholder="Street, city, postal code" /></label></div>}{stage === 'payment' && <fieldset className="payment-options"><legend><CreditCard /> Sandbox payment</legend><label><input type="radio" checked={payment === 'Sandbox card'} onChange={() => setPayment('Sandbox card')} /> Sandbox card</label><label><input type="radio" checked={payment === 'Cash on delivery'} onChange={() => setPayment('Cash on delivery')} /> Cash on delivery</label></fieldset>}{stage === 'review' && <div className="review-box"><p><ShieldCheck /> Exact products, sellers, quantities, and prices are shown below.</p>{cart.map(item => <p key={item.product.id}>{item.product.title} · {item.product.store} · {item.quantity} × {money(item.product)}</p>)}<p>Subtotal: {money(cart[0].product, subtotal)}</p><p>Shipping: {shipping ? money(cart[0].product, shipping) : 'Free'}</p><p>Tax: {money(cart[0].product, tax)}</p><p className="review-total">Total: {money(cart[0].product, total)}</p></div>}{message && <p className="checkout-message" role="alert">{message}</p>}<div className="checkout-actions"><button type="button" className="text-button" onClick={() => setStage(stage === 'cart' ? 'cart' : stage === 'delivery' ? 'cart' : stage === 'payment' ? 'delivery' : 'payment')}><ArrowLeft /> Back</button><button type="button" className="shortlist-button" onClick={stage === 'review' ? confirm : next}>{stage === 'review' ? 'Confirm & Place Order' : 'Continue'} </button></div></div></section>
}
